### ISSUE TITLE
Restrict access border windows overlapping with text

### ISSUE THREAD

**Issue by nchan31** [cca/moodle-styles#28]
<img width="823" alt="Screen Shot 2023-05-10 at 2 34 38 PM" src="https://github.com/cca/moodle-styles/assets/93795394/73c02b80-6bc5-4a8b-817c-92509cf401f8">
elements not aligned or overlapping in restrict access settings

**Comment by phette23** [comment]
<img width="966" alt="Screenshot 2023-05-16 at 2 15 39 PM" src="https://github.com/cca/moodle-styles/assets/1024833/b43e569d-4900-4a66-b961-6c2142620cf4">

Disabling the padding-left on the eye icon `.mform fieldset .fcontainer.collapseable .col-form-label` seems to fix this, but might have side effects. We may want to target that selector so it only affects access restriction forms instead of _all_ Moodle forms.

**Comment by phette23** [comment]
@nchan31 I have a fix for this up on staging. I think it should only affect the restrict access "eye" icon while editing page settings, so unlikely to affect other areas. I tried a few combinations of access restrictions, some nested rules, and it all seemed to look better. If you have a chance to test it too, I will apply the fix to production.

**Comment by nchan31** [comment]
@phette23 I don't see the fix on staging on my side atm, but I'm not sure if maybe you disabled it due to issues with something else on the site. Thanks for looking at this! Date restriction also looks a bit jumbled as well - the new Moodle 4 squished these boxes unfortunately. This is in staging, on a page activity:
![image](https://github.com/cca/moodle-styles/assets/93795394/ae712ef8-5fcf-4357-bc05-29db8ac753c6)

**Comment by phette23** [comment]
So I was using a CSS selector that only targeted assignments. I can fix that to target all activities, but if you have both the navigation and blocks sidebars open, there's still this awkward overflow:
<img width="578" alt="Screenshot 2023-06-21 at 3 53 49 PM" src="https://github.com/cca/moodle-styles/assets/1024833/f01888c0-e34d-4cff-b76f-0bd8364e19b4">

I'm researching how to fix this, I think it's possible. It seemed like [this post](https://stackoverflow.com/questions/36230944/prevent-flex-items-from-overflowing-a-container) on a nuance of the flex layout used here might help, but I've tried giving a bunch of different elements `min-width: 0` and it did not help.

**Comment by phette23** [comment]
OK I can add a rule like

```css
.mform .form-inline .form-group {
    width: calc(100% + 1rem);
}
```

which causes the two select inputs in an Activity Completion condition to break onto two lines if both sidebars are expanded, but collapse onto a single line if there's room enough (which should be when one sidebar is collapsed on a laptop-sized screen).
![eye width fix](https://github.com/cca/moodle-styles/assets/1024833/1e5bd452-ce3c-4b97-84d0-28399b20db71)

Explanation: without a width the children of this form group don't seem to know/respect its boundaries, they overflow it and its parents elements causing this overlap issue. A width of `100%` prevents overlap but the inputs split over two lines because there's never enough width for both to fit. However, the parent `<span class="form-inline availability_completion availability-plugincontrols">` element has `padding: 1rem` and we can use the right side of that padding (so 1rem of the 2rem total horizontal padding) to give its child just enough width to fit both the grandchildren.

After we removed the eye icon padding, the overlap issue seems limited to Activity Completion conditions, in my testing.
